spring:
    application:
        name: loan
    datasource:
        username: sa
        password:
        url: jdbc:h2:mem:testdb
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
server:
    port: 9005

management:
    endpoints:
        web:
            exposure:
                include: '*'
    info:
        env:
            enabled: true
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:9002/eureka/

info:
    app:
        name: "loan-service"
        description: "Java Express Loan microservice"
        version: "1.0.0"