spring:
    application:
        name: eurekaserver
server:
    port: 9002
    
eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://localhost:9002/eureka/
management:
    endpoints:
        web:
            exposure:
                include: '*'